### PR TITLE
Review of initial code

### PR DESCRIPTION
**Pull request by BluCodeGH**
**Note:** There is some funky git stuff going on since I put the initial code on the `gh-pages` branch to get it working. Basically this PR is comparing two totally independent branches, so once approved we'll close without merging.

This is a first iteration of an electrical parts tracking system. It is currently live at https://parts.waterloorocketry.com. Some of the main features:
- Pulls data from a google sheet in the drive: https://docs.google.com/spreadsheets/d/1NLXdFrLtgda5LWzMhjwzs9EuQLDXqR4jcgIqeNbPJr8/edit?usp=sharing
- Works offline in most browsers (brave with extensions has issues apparently). Once you've opened it once, it caches itself and the data from the sheet, so if you turn off your wifi you should be able to reload the page and still search/filter/sort as normal. **Please test this on your device, I've only tested on linux and android.**
- The search bar filters by value within 10% tolerance (eg you can type 10.1k and it will show you 10k), along with fuzzy searching.
- You can sort by any column by clicking on the header.

Some of the next steps for this are:
- Redirecting the http url to https
- Better table display on mobile, right now the font is tiny
- Being able to click into parts on the table for more details / linking to digikey / something
- Adding new parts via this UI and google oauth sign-in (where it searches for similar parts to prevent duplicates)

Also please keep in mind I have no idea what I'm doing when it comes to frontend so I've probability committed terrible malpractice somewhere.

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/parts.website/1)

### CODE REVIEW

**Review by Darth-Raazi — CHANGES_REQUESTED** [review]
This is pretty sick, I like the way you handled offline mode and the searching is really good. Couple thoughts:
- I'm not sure if this is possible with the current scripts, but could we have some sort of constant network checker? Currently after disconnecting/reconnecting to a network, the page needs to be reloaded for warning to appear/disappear and sheets/cache to be used. It would be nice to have it update in real-time
- Alignment of content with column headers is a bit off, I think either centering the content or putting in divider lines for the columns would help, especially on mobile
- Obviously for a first implementation the look and feel isn't super important, but going forward, adding some more styling to the table and page in general (dividers, borders, colours, etc.) is a good idea

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/parts.website/1#-:-Nmi6OHtD0KACGwCD8MT:buio2qt)* status: all files reviewed, 3 unresolved discussions (waiting on @BluCodeGH, @DomenicHampson, @KavinSatheeskumar, and @QuantumManiac)

___
*[`index.css` line 5 at r1](https://reviewable.io/reviews/waterloo-rocketry/parts.website/1#-Nmi4GOJ534b4JicEGcr:-Nmi4GOJ534b4JicEGcs:bnywxuq) ([raw file](https://github.com/waterloo-rocketry/parts.website/blob/81ae8cace0a25205b886116eed1c2dcd0f7b6a8b/index.css#L5)):*
> ```CSS
> }
> 
> #offline_warning {
> ```

Personal preference: I think the warning would look better centered
___
*[`index.html` line 11 at r1](https://reviewable.io/reviews/waterloo-rocketry/parts.website/1#-Nmi5XcBBAbQVEfNBmLi:-Nmi5XcBBAbQVEfNBmLj:b-e73bid) ([raw file](https://github.com/waterloo-rocketry/parts.website/blob/81ae8cace0a25205b886116eed1c2dcd0f7b6a8b/index.html#L11)):*
> ```HTML
>     <body>
>         <div id="offline_warning">
>             <p><b>Warning:</b> You are offline.</p>
> ```

Would a more descriptive message be better? Something like: 
```
Offline Mode: Displaying cached values, data might not be up-to-date
```
___
*[`index.html` line 19 at r1](https://reviewable.io/reviews/waterloo-rocketry/parts.website/1#-Nmi2XedCo5E69WRz-xF:-Nmi2XedCo5E69WRz-xG:b-tmcwhb) ([raw file](https://github.com/waterloo-rocketry/parts.website/blob/81ae8cace0a25205b886116eed1c2dcd0f7b6a8b/index.html#L19)):*
> ```HTML
>             <table id="parts_table">
>                 <tr>
>                     <th onclick="sort_parts('value')">Part</th>
> ```

I'd like some arrows or other sorting indicators beside the names of the columns. That way it would be more apparent to the user which column (if any) are currently being used for sorting and in which direction

**Review by QuantumManiac — CHANGES_REQUESTED** [review]
LGTM so far! Just left a few comments, mostly just nits and styling stuff

Tested and works on
- Brave + Linux
- Brave + Windows (Brave with extensions _does not_ have issues, it was something else that was the problem)
- MS Edge + Windows
- Safari + iOS

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/parts.website/1#-:-NmkkMmj6gaOkZtgunZg:b38tm0p)* status: all files reviewed, 8 unresolved discussions (waiting on @BluCodeGH, @Darth-Raazi, @DomenicHampson, and @KavinSatheeskumar)

___
*[`index.css` line 5 at r1](https://reviewable.io/reviews/waterloo-rocketry/parts.website/1#-Nmkm1EDEABmGXlApSYt:-Nmkm1EDEABmGXlApSYu:btjdrio) ([raw file](https://github.com/waterloo-rocketry/parts.website/blob/81ae8cace0a25205b886116eed1c2dcd0f7b6a8b/index.css#L5)):*
> ```CSS
> }
> 
> #offline_warning {
> ```

nit: CSS classes and IDs are usually in kebab-case
___
*[`index.css` line 52 at r1](https://reviewable.io/reviews/waterloo-rocketry/parts.website/1#-NmklLaA1ZErqPbnkh3p:-NmklLaA1ZErqPbnkh3q:bwjx1na) ([raw file](https://github.com/waterloo-rocketry/parts.website/blob/81ae8cace0a25205b886116eed1c2dcd0f7b6a8b/index.css#L52)):*
> ```CSS
> 
> /* parts table column widths */
> th:nth-of-type(1) {width: 20%}
> ```

It might be a good idea to give your `th` a class instead of styling all of them, just in case we do end up having more tables on the page in the future for some reason. Alternatively, just add `style` tags to the `th` directly?
___
*[`index.html` line 2 at r1](https://reviewable.io/reviews/waterloo-rocketry/parts.website/1#-NmkmQwWDaE40WDI0h6P:-NmkmQwWDaE40WDI0h6Q:b-7m6t4s) ([raw file](https://github.com/waterloo-rocketry/parts.website/blob/81ae8cace0a25205b886116eed1c2dcd0f7b6a8b/index.html#L2)):*
> ```HTML
> <!DOCTYPE html>
> <html>
> ```

nit:



_Suggestion:_
```HTML
<html lang="en">
```
___
*[`index.html` line 11 at r1](https://reviewable.io/reviews/waterloo-rocketry/parts.website/1#-Nmi5XcBBAbQVEfNBmLi:-Nmklo1xA36ZSDpaECtU:b32v57) ([raw file](https://github.com/waterloo-rocketry/parts.website/blob/81ae8cace0a25205b886116eed1c2dcd0f7b6a8b/index.html#L11)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

Would a more descriptive message be better? Something like: 
```
Offline Mode: Displaying cached values, data might not be up-to-date
```
</blockquote></details>

+1
___
*[`index.html` line 19 at r1](https://reviewable.io/reviews/waterloo-rocketry/parts.website/1#-Nmi2XedCo5E69WRz-xF:-NmklpcNAVL5Arr7J19h:b32v57) ([raw file](https://github.com/waterloo-rocketry/parts.website/blob/81ae8cace0a25205b886116eed1c2dcd0f7b6a8b/index.html#L19)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

I'd like some arrows or other sorting indicators beside the names of the columns. That way it would be more apparent to the user which column (if any) are currently being used for sorting and in which direction
</blockquote></details>

+1
___
*[`main.js` line 16 at r1](https://reviewable.io/reviews/waterloo-rocketry/parts.website/1#-NmkojYACD5iOO_9Lo5p:-NmkojYACD5iOO_9Lo5q:btg2z0l) ([raw file](https://github.com/waterloo-rocketry/parts.website/blob/81ae8cace0a25205b886116eed1c2dcd0f7b6a8b/main.js#L16)):*
> ```JavaScript
> let parts; // Array of all the part objects we loaded
> let filtered; // Subset of parts that matches the user's search
> let fuse; // index to quickly fuzzy search over parts
> ```

lol, this was confusing for a sec until I remembered that fuse.js is being used for fuzzy searching. 
___
*[`main.js` line 55 at r1](https://reviewable.io/reviews/waterloo-rocketry/parts.website/1#-NmkoueP0J258L1Mkrqe:-NmkoueQ1B3-luFe6pni:b-bbqlyx) ([raw file](https://github.com/waterloo-rocketry/parts.website/blob/81ae8cace0a25205b886116eed1c2dcd0f7b6a8b/main.js#L55)):*
> ```JavaScript
> 
> // Called on keyup in the search box
> function filter_parts() {
> ```

nit: JS functions should be in camelCase.

Also, it might be good to write up some JSDocs for the functions that you have written.

**Review by BluCodeGH — COMMENTED** [review]
- We can definitely open an issue for periodic online checking, but it wouldn't be trivial since how you load data would need to change a decent bit.
- Added dividers, but yeah I agree someone who enjoys CSS should take a swing at making it look better.

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/parts.website/1#-:-NmmXd4OAOQGmBl15RvD:b-wy1mwi)* status: 4 of 10 files reviewed, 5 unresolved discussions (waiting on @Darth-Raazi, @DomenicHampson, @KavinSatheeskumar, and @QuantumManiac)

___
*[`index.css` line 5 at r1](https://reviewable.io/reviews/waterloo-rocketry/parts.website/1#-Nmi4GOJ534b4JicEGcr:-NmmX8jD6na3wrRqDiZ_:bb6un1j) ([raw file](https://github.com/waterloo-rocketry/parts.website/blob/81ae8cace0a25205b886116eed1c2dcd0f7b6a8b/index.css#L5)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

Personal preference: I think the warning would look better centered
</blockquote></details>

Done
___
*[`index.css` line 5 at r1](https://reviewable.io/reviews/waterloo-rocketry/parts.website/1#-Nmkm1EDEABmGXlApSYt:-NmmX9OK31krl1t7vG4Q:bb6un1j) ([raw file](https://github.com/waterloo-rocketry/parts.website/blob/81ae8cace0a25205b886116eed1c2dcd0f7b6a8b/index.css#L5)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

nit: CSS classes and IDs are usually in kebab-case
</blockquote></details>

Done
___
*[`index.css` line 52 at r1](https://reviewable.io/reviews/waterloo-rocketry/parts.website/1#-NmklLaA1ZErqPbnkh3p:-NmmXALFAUCJKib_bniO:bb6un1j) ([raw file](https://github.com/waterloo-rocketry/parts.website/blob/81ae8cace0a25205b886116eed1c2dcd0f7b6a8b/index.css#L52)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

It might be a good idea to give your `th` a class instead of styling all of them, just in case we do end up having more tables on the page in the future for some reason. Alternatively, just add `style` tags to the `th` directly?
</blockquote></details>

Done
___
*[`index.html` line 2 at r1](https://reviewable.io/reviews/waterloo-rocketry/parts.website/1#-NmkmQwWDaE40WDI0h6P:-NmmXDjbEwxYbh1wRXDq:bb6un1j) ([raw file](https://github.com/waterloo-rocketry/parts.website/blob/81ae8cace0a25205b886116eed1c2dcd0f7b6a8b/index.html#L2)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

nit:
</blockquote></details>

Done
___
*[`index.html` line 11 at r1](https://reviewable.io/reviews/waterloo-rocketry/parts.website/1#-Nmi5XcBBAbQVEfNBmLi:-NmmXEPM6V5NrxUacm4J:bb6un1j) ([raw file](https://github.com/waterloo-rocketry/parts.website/blob/81ae8cace0a25205b886116eed1c2dcd0f7b6a8b/index.html#L11)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done
___
*[`index.html` line 19 at r1](https://reviewable.io/reviews/waterloo-rocketry/parts.website/1#-Nmi2XedCo5E69WRz-xF:-NmmXFB1D-ZLo71doad6:bb6un1j) ([raw file](https://github.com/waterloo-rocketry/parts.website/blob/81ae8cace0a25205b886116eed1c2dcd0f7b6a8b/index.html#L19)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done
___
*[`main.js` line 16 at r1](https://reviewable.io/reviews/waterloo-rocketry/parts.website/1#-NmkojYACD5iOO_9Lo5p:-NmmXG4T--P3hjCL2Qvq:b-lk1e2k) ([raw file](https://github.com/waterloo-rocketry/parts.website/blob/81ae8cace0a25205b886116eed1c2dcd0f7b6a8b/main.js#L16)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

lol, this was confusing for a sec until I remembered that fuse.js is being used for fuzzy searching.
</blockquote></details>

Did you mean to block on this?
___
*[`main.js` line 55 at r1](https://reviewable.io/reviews/waterloo-rocketry/parts.website/1#-NmkoueP0J258L1Mkrqe:-NmmXOIjET7I0VTrzq2G:b-w1qce0) ([raw file](https://github.com/waterloo-rocketry/parts.website/blob/81ae8cace0a25205b886116eed1c2dcd0f7b6a8b/main.js#L55)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

nit: JS functions should be in camelCase.

Also, it might be good to write up some JSDocs for the functions that you have written.
</blockquote></details>

Fixed case. I'm lazy and it doesn't feel like JSDocs would be useful at this stage.

**Review by Darth-Raazi — APPROVED** [review]
Forgot to mention I tested on Brave + macOS. As mentioned by Chamath, extensions are not an issue

:lgtm:

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/parts.website/1#-:-NmnJ0Nk9ut7j76m_0mt:bj37x5z)* status: all files reviewed, 2 unresolved discussions (waiting on @DomenicHampson, @KavinSatheeskumar, and @QuantumManiac)

**Review by QuantumManiac — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/parts.website/1#-:-Nmq1kY0BTjwOwvAFAsL:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DomenicHampson and @KavinSatheeskumar)

___
*[`main.js` line 16 at r1](https://reviewable.io/reviews/waterloo-rocketry/parts.website/1#-NmkojYACD5iOO_9Lo5p:-Nmq1_067HYw0FD3r6-I:b8y6y6n) ([raw file](https://github.com/waterloo-rocketry/parts.website/blob/81ae8cace0a25205b886116eed1c2dcd0f7b6a8b/main.js#L16)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Did you mean to block on this?
</blockquote></details>

Nope, forgot to set the correct disposition.

**Comment by BluCodeGH** [comment]
Counting that as approved and closing since code is already on gh-pages.

**Pull request closed without merging**
